### ISSUE TITLE
Bug : Navigation Icons Not Visible

### ISSUE THREAD

**Issue by vlv3k** [vlv3k/Signal-App#1]
The navigation icons on the website are currently not visible. This issue aims to address and fix the problem to ensure a seamless user experience.

Acceptance Criteria:

`Verify that the navigation icons are visible on the homepage.`
`Check that the navigation icons remain visible on different browsers (Chrome, Firefox, Safari).`
`Ensure that the icons are displayed correctly on various devices (desktop, tablet, mobile).`
`Confirm that the icons are clickable and lead to the respective navigation destinations.`

![image](https://github.com/vlv3k/Signal-App/assets/146809845/cee64563-28d5-4532-a742-1a8d117d4b7a)

**Comment by HarineMurugan** [comment]
Fixed. Raised PR - https://github.com/vlv3k/Signal-App/pull/4

![image](https://github.com/vlv3k/Signal-App/assets/92710085/ad10854d-39b9-4fc6-94ff-6662db6e908f)

**Comment by HarineMurugan** [comment]
Hi @vlv3k 
I am unable to access https://github.com/vlv3k/Signal-App/blob/main/CONTRIBUTING.md
Please let me know if this is fine, or any other rules are there

**Comment by vlv3k** [comment]
> Hi @vlv3k I am unable to access https://github.com/vlv3k/Signal-App/blob/main/CONTRIBUTING.md Please let me know if this is fine, or any other rules are there

no It's Fine 

You can also check this repository - **https://github.com/boorge/kiran**  For more open source contribution
