### ISSUE TITLE
Bug : Speak Freely

### ISSUE THREAD

**Issue by vlv3k** [vlv3k/Signal-App#2]
Heading font size is very small. Ensure that the font size for the "Speak Freely" heading is set to the smallest possible size.

` The font size of the "Speak Freely" heading is set to the smallest possible size.`

![image](https://github.com/vlv3k/Signal-App/assets/146809845/562478df-4b54-42ff-b490-a363792e96dc)

**Comment by boorge** [comment]
Assign me this Topic
