### ISSUE TITLE
Button [Get Signal] Margin Problem

### ISSUE THREAD

**Issue by vlv3k** [vlv3k/Signal-App#3]
The margin for the "Get Signal" button is not displaying correctly, causing a visual issue in the user interface.

Acceptance Criteria:

` Verify that the margin for the "Get Signal" button is consistent across different screen sizes.`
` Ensure that the button's margin aligns with the design specifications.`
` Confirm that the margin issue is resolved in both desktop and mobile views.`

![image](https://github.com/vlv3k/Signal-App/assets/146809845/c73b034a-803b-45f0-8dcf-159617fe0140)

**Comment by boorge** [comment]
Assign Me this Issue
