### ISSUE TITLE
Future : Add Button Hover Effect

### ISSUE THREAD

**Issue by vlv3k** [vlv3k/Signal-App#8]
Implement a hover effect for buttons to enhance the user experience. When a user hovers over a button, it should change its appearance to provide visual feedback.

 `Buttons change color on hover.`
` Transition duration is smooth and visually appealing.`
` Hover effect is consistent across all buttons.`
` The hover effect is compatible with different button styles (primary, secondary, etc.).`

![image](https://github.com/vlv3k/Signal-App/assets/146809845/0e7807a8-abc3-4610-b3ec-2b22d9893593)

**Comment by boorge** [comment]
Assign Me
